(function(){
"use strict";
var operators=Array.isArray(globalThis.ARKNIGHTS_OPERATORS)?globalThis.ARKNIGHTS_OPERATORS:[],MAX=10,KEY="arknights-friberg.game.v1";
var $=function(s){return document.querySelector(s)},el={form:$("#guessForm"),input:$("#operatorSearch"),results:$("#searchResults"),rows:$("#guessRows"),wrap:$("#boardWrap"),empty:$("#boardEmpty"),count:$("#guessCount"),progress:$("#progressBar"),status:$("#roundStatus"),dots:$("#roundDots"),result:$("#gameResult"),newGame:$("#newGame"),rules:$("#rulesModal"),openRules:$("#openRules"),closeRules:$("#closeRules"),toast:$("#toast")};
var state={targetId:null,guesses:[],status:"playing"},selected=null,index=-1,timer;
function esc(v){return String(v==null?"":v).replace(/[&<>'"]/g,function(c){return{"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]})}
function norm(v){return String(v||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[\s'’._-]/g,"")}
function byId(id){return operators.find(function(x){return x.id===id})||null}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch(e){}}
function newTarget(except){var p=operators.filter(function(x){return x.id!==except});return p[Math.floor(Math.random()*p.length)]||operators[0]}
function load(){try{var x=JSON.parse(localStorage.getItem(KEY)||"null");if(x&&byId(x.targetId)&&Array.isArray(x.guesses)&&x.guesses.every(byId)&&["playing","won","lost"].includes(x.status)){state={targetId:x.targetId,guesses:x.guesses.slice(0,MAX),status:x.status};return}}catch(e){}var t=newTarget();state={targetId:t?t.id:null,guesses:[],status:"playing"};save()}
function toast(s){clearTimeout(timer);el.toast.textContent=s;el.toast.classList.add("show");timer=setTimeout(function(){el.toast.classList.remove("show")},2500)}
function setHas(a,b){a=(a||[]).slice().sort();b=(b||[]).slice().sort();return a.length===b.length&&a.every(function(x,i){return x===b[i]})}
function overlap(a,b){return(a||[]).some(function(x){return(b||[]).includes(x)})}
function compare(a,b,f){if(a.id===b.id)return"exact";if(f==="rarity")return a.rarity===b.rarity?"exact":Math.abs(a.rarity-b.rarity)===1?"close":"miss";if(f==="class")return a.class===b.class?"exact":"miss";if(f==="subclass")return a.subclass===b.subclass?"exact":a.class===b.class?"close":"miss";if(f==="faction")return a.faction===b.faction?"exact":a.group===b.group?"close":"miss";if(f==="year")return a.year===b.year?"exact":Math.abs(a.year-b.year)===1?"close":"miss";if(f==="tags")return setHas(a.tags,b.tags)?"exact":overlap(a.tags,b.tags)?"close":"miss";if(f==="position")return setHas(a.position,b.position)?"exact":overlap(a.position,b.position)?"close":"miss";if(f==="alter")return Boolean(a.hasAlter)===Boolean(b.hasAlter)?"exact":"miss";return"miss"}
function arrow(a,b){return a===b?"":'<span class="direction">'+(b>a?"↑":"↓")+"</span>"}
function alterText(o){return o.hasAlter?"有":"无"}
function cell(f,v,a,b){return'<td class="'+compare(a,b,f)+'">'+v+"</td>"}
function row(a,b){var stars=String.fromCodePoint(9733).repeat(a.rarity);return"<tr>"+'<td class="'+(a.id===b.id?"exact":"miss")+'"><b>'+esc(a.name)+"</b><small>"+esc(a.en)+"</small></td>"+cell("rarity",'<span class="stars">'+stars+"</span>"+arrow(a.rarity,b.rarity),a,b)+cell("class",esc(a.class),a,b)+cell("subclass",esc(a.subclass),a,b)+cell("faction",esc(a.faction)+"<small>"+esc(a.group)+"</small>",a,b)+cell("year",a.year+arrow(a.year,b.year),a,b)+cell("tags",'<span class="tags">'+esc(a.tags.join(" · "))+"</span>",a,b)+cell("position",esc(a.position.join(" / ")),a,b)+cell("alter",esc(alterText(a)),a,b)+"</tr>"}
function render(){var target=byId(state.targetId),guesses=state.guesses.map(byId).filter(Boolean);el.count.textContent=guesses.length;el.progress.style.width=(guesses.length/MAX*100)+"%";el.dots.innerHTML=Array.from({length:MAX},function(_,i){return'<i class="'+(i<guesses.length?(state.status==="lost"&&i===guesses.length-1?"failed":"used"):"")+'"></i>'}).join("");el.empty.hidden=guesses.length>0;el.wrap.hidden=!guesses.length;el.rows.innerHTML=guesses.map(function(g){return row(g,target)}).join("");el.input.disabled=state.status!=="playing";el.form.querySelector("button[type=submit]").disabled=state.status!=="playing";if(state.status==="won"){el.status.textContent="识别成功 · "+guesses.length+" 次";el.result.className="ak-result win";el.result.hidden=false;el.result.innerHTML="<strong>目标已确认：<b>"+esc(target.name)+"</b></strong><p>"+esc(target.en)+" · "+target.rarity+"★ "+esc(target.class)+" / "+esc(target.subclass)+"</p>"}else if(state.status==="lost"){el.status.textContent="识别失败 · 已达上限";el.result.className="ak-result lose";el.result.hidden=false;el.result.innerHTML="<strong>本轮目标：<b>"+esc(target.name)+"</b></strong><p>"+esc(target.en)+" · 点击“换一位目标”开始新一轮。</p>"}else{el.status.textContent=guesses.length?"识别进行中 · 还剩 "+(MAX-guesses.length)+" 次":"等待第一次识别";el.result.hidden=true}}
function matches(q){q=norm(q);if(!q)return[];return operators.filter(function(o){return[o.name,o.en,o.id].some(function(x){return norm(x).includes(q)})&&!state.guesses.includes(o.id)}).sort(function(a,b){return a.name.localeCompare(b.name,"zh-CN")}).slice(0,9)}
function search(){var found=matches(el.input.value);el.results.innerHTML=found.map(function(o,i){return'<button type="button" role="option" class="'+(i===index?"active":"")+'" data-operator="'+esc(o.id)+'"><b>'+esc(o.name)+"</b><small>"+esc(o.en)+" · "+esc(o.class)+" / "+esc(o.subclass)+"</small><span>"+o.rarity+"★</span></button>"}).join("");el.results.classList.toggle("open",found.length>0&&state.status==="playing")}
function select(id){var o=byId(id);if(!o)return;selected=o.id;el.input.value=o.name;el.results.classList.remove("open")}
function submit(){if(state.status!=="playing")return;var q=norm(el.input.value),o=byId(selected)||operators.find(function(x){return[x.name,x.en,x.id].some(function(v){return norm(v)===q})});if(!o){toast("请从下拉列表中选择一位干员");search();return}if(state.guesses.includes(o.id)){toast("这位干员已经猜过了");return}state.guesses.push(o.id);if(o.id===state.targetId)state.status="won";else if(state.guesses.length>=MAX)state.status="lost";selected=null;el.input.value="";save();el.results.classList.remove("open");render()}
function reset(){if(state.guesses.length&&state.status==="playing"&&!confirm("当前进度会被清空，确定更换目标吗？"))return;var t=newTarget(state.targetId);state={targetId:t?t.id:null,guesses:[],status:"playing"};selected=null;el.input.value="";save();render();el.input.focus();toast("已选择新的目标干员")}
el.input.addEventListener("input",function(){selected=null;index=-1;search()});el.input.addEventListener("focus",search);el.input.addEventListener("keydown",function(e){var a=matches(el.input.value);if(e.key==="ArrowDown"){e.preventDefault();index=Math.min(index+1,a.length-1);search()}else if(e.key==="ArrowUp"){e.preventDefault();index=Math.max(0,index-1);search()}else if(e.key==="Enter"&&index>=0&&a[index]){e.preventDefault();select(a[index].id)}else if(e.key==="Escape")el.results.classList.remove("open")});el.results.addEventListener("click",function(e){var b=e.target.closest("[data-operator]");if(b)select(b.dataset.operator)});el.form.addEventListener("submit",function(e){e.preventDefault();submit()});el.newGame.addEventListener("click",reset);document.addEventListener("click",function(e){if(!e.target.closest(".ak-search"))el.results.classList.remove("open")});function rules(open){el.rules.hidden=!open;document.body.style.overflow=open?"hidden":""}el.openRules.addEventListener("click",function(){rules(true)});el.closeRules.addEventListener("click",function(){rules(false)});el.rules.addEventListener("click",function(e){if(e.target===el.rules)rules(false)});document.addEventListener("keydown",function(e){if(e.key==="Escape"&&!el.rules.hidden)rules(false)});
if(!operators.length){el.input.disabled=true;el.status.textContent="题库加载失败";toast("未能加载干员题库");return}load();render()
}());
