import assert from "node:assert/strict";
import { createAppServer } from "../app-server.mjs";

const players = Array.from({ length:60 }, (_, index) => ({
  id:index === 0 ? "Answer" : `P${index}`,
  team:index % 2 ? "A" : "B",
  country:"France",
  region:"Europe",
  age:18 + index % 20,
  role:index % 3 ? "Rifler" : "AWPer",
  majorWins:index % 2,
  majorApps:index % 8,
  status:"active"
}));
players[1].team="|roles=awp";
const app = await createAppServer({ players, apiKey:null, disableInitialSync:true, gameOptions:{ random:()=>0 } });
await new Promise((resolve,reject)=>{ app.server.once("error",reject); app.server.listen(0,"127.0.0.1",resolve); });
const base = `http://127.0.0.1:${app.server.address().port}`;
const jsonHeaders = { "Content-Type":"application/json" };
const playerHeaders = token => ({ ...jsonHeaders, "X-Player-Token":token });

try {
  let response = await fetch(base + "/healthz");
  assert.equal(response.status, 200);
  assert.deepEqual(await response.json(), { ok:true });

  response = await fetch(base + "/api/players");
  const publicPlayers = (await response.json()).players;
  assert.equal(publicPlayers.find(player=>player.id==="P1").team, "无队伍");

  response = await fetch(base + "/");
  assert.equal(response.status, 200);
  const homeHtml = await response.text();
  assert.match(homeHtml, /选择游戏/);
  assert.match(homeHtml, /href="\/play"/);
  assert.match(homeHtml, /href="\/arknights"/);

  response = await fetch(base + "/play");
  assert.equal(response.status, 200);
  const playHtml = await response.text();
  assert.match(playHtml, /id="roomMaxPlayers"/);
  assert.match(playHtml, /id="roomScoreToWin"/);
  assert.match(playHtml, /id="roomRoundDuration"/);
  assert.match(playHtml, /inputmode="numeric"/);
  assert.match(playHtml, /id="roomCreatedModal"/);
  assert.ok(playHtml.indexOf('id="roomCreatedModal"') < playHtml.indexOf('<script src="js/game.js"'));
  assert.equal((playHtml.match(/value="beginner"/g)||[]).length, 3);
  assert.doesNotMatch(playHtml, /id="matchSeries"/);
  assert.match(playHtml, /class="match-format-lock"/);
  assert.doesNotMatch(playHtml, /class="mode-tabs"/);
  assert.equal((playHtml.match(/data-view=/g)||[]).length, 3);
  assert.match(playHtml, /id="view-home"/);
  assert.match(playHtml, /class="site-header app-header"/);
  assert.match(playHtml, /class="logo app-brand"/);
  assert.match(playHtml, /nav class="primary-nav"/);
  assert.match(playHtml, /class="header-actions"/);
  assert.ok(playHtml.indexOf('<script src="js/flags.js"></script>') < playHtml.indexOf('<script src="js/game.js"></script>'));
  assert.equal((playHtml.match(/class="home-mode-card"/g)||[]).length, 3);
  assert.match(playHtml, /id="openRules"/);
  assert.match(playHtml, /id="rulesModal"/);
  assert.match(playHtml, /id="gameToast" role="status" aria-live="polite"/);
  assert.match(playHtml, /id="roomInviteModal"/);
  assert.match(playHtml, /id="roomInviteName"/);
  assert.equal((playHtml.match(/class="region-rule-item /g)||[]).length, 7);
  assert.match(playHtml, /class="rules-fields"/);
  assert.match(playHtml, /class="field-rule field-rule-exact"/);
  assert.match(playHtml, /class="field-rule field-rule-close"/);
  assert.match(playHtml, /class="room-option-enter room-option-host"/);
  assert.match(playHtml, /class="tool-cta" href="\/tool" target="_blank" rel="noopener"/);
  const headerNav = playHtml.match(/<header class="site-header app-header">[\s\S]*?<nav class="primary-nav">([\s\S]*?)<\/nav>/)?.[1] || "";
  assert.doesNotMatch(headerNav, /<button/);

  response = await fetch(base + "/js/game.js");
  assert.equal(response.status, 200);
  const gameSource = await response.text();
  assert.match(gameSource, /composerEditing/);
  assert.match(gameSource, /setRoomReady/);
  assert.match(gameSource, /startPrivateRoom/);
  assert.match(gameSource, /multiplayer-scoreboard/);
  assert.match(gameSource, /game-result-overlay/);
  assert.match(gameSource, /aria-modal/);
  assert.match(gameSource, /updateLiveRoom/);
  assert.match(gameSource, /roundChanged/);
  assert.match(gameSource, /id="viewMatch"/);
  assert.match(gameSource, /id="viewRound"/);
  assert.match(gameSource, /id="viewSingle"/);
  assert.match(gameSource, /查看全部对局/);
  assert.match(gameSource, /function matchHistory/);
  assert.match(gameSource, /series=3/);
  assert.match(gameSource, /view:"home"/);
  assert.match(gameSource, /function returnHome/);
  assert.match(gameSource, /function setRulesOpen/);
  assert.match(gameSource, /\.mode-back/);
  assert.match(gameSource, /id="showResult"/);
  assert.match(gameSource, /ROOM_SESSION_KEY/);
  assert.match(gameSource, /persistRoomAuth/);
  assert.match(gameSource, /reconnectSavedRoom/);
  assert.match(gameSource, /id="reconnectRoom"/);
  assert.match(gameSource, /id="roomScoreboard"/);
  assert.match(gameSource, /id="roomBoards"/);
  assert.match(gameSource, /boards\.innerHTML=multiplayerBoards/);
  assert.match(gameSource, /function guessRowKeys/);
  assert.match(gameSource, /animateNewGuessRows/);
  assert.match(gameSource, /class="direction \$\{directionClass\}"/);
  assert.match(gameSource, /data-guess-key/);
  assert.match(gameSource, /data-label/);
  assert.match(gameSource, /data-field/);
  assert.ok(gameSource.includes('Flags.flag(p.country,"guess-flag")'));
  assert.match(gameSource, /class="col-country"/);
  assert.match(gameSource, /round_settling/);
  assert.match(gameSource, /roundIntermissionLeftMs/);
  assert.match(gameSource, /roundDurationSeconds/);
  assert.match(gameSource, /下一局将在/);
  assert.match(gameSource, /let submitting=false/);
  assert.match(gameSource, /await submitPlayer\(button\.dataset\.player\)/);
  assert.match(gameSource, /bindGuessSearch\(guessSingle\)/);
  assert.match(gameSource, /bindGuessSearch\(guessRoom\)/);
  assert.match(gameSource, /revealSingle/);
  assert.match(gameSource, /leaveCurrentRoom/);
  assert.match(gameSource, /function beginnerEligible/);
  assert.match(gameSource, /questionEligible/);
  assert.match(gameSource, /text\.length>18\?3800:2600/);
  assert.match(gameSource, /mode==="beginner"/);
  assert.match(gameSource, /id="leaveRoom"/);
  assert.match(gameSource, /data-kick-player/);
  assert.match(gameSource, /\/kick/);
  assert.match(gameSource, /board-update/);
  assert.match(gameSource, /pendingInvite/);
  assert.match(gameSource, /function accessRoom/);
  assert.match(gameSource, /function roomInviteText/);
  assert.match(gameSource, /GameConfig\.inviteBrand\|\|"PR弗一把"/);
  assert.match(gameSource, /copyRoomInvite\(room,me,false\)/);
  assert.match(gameSource, /copyRoomInvite\(room,me,true\)/);
  assert.match(gameSource, /function showRoomInvite/);
  assert.match(gameSource, /function animateLobbyChanges/);
  assert.match(gameSource, /private-lobby-layout/);
  assert.match(gameSource, /function runUiTransition/);
  assert.match(gameSource, /document\.startViewTransition/);
  assert.match(gameSource, /transitionDirection/);


  response = await fetch(base + "/tool");
  assert.equal(response.status, 200);
  const toolHtml = await response.text();
  assert.match(toolHtml, /class="topbar app-header"/);
  assert.match(toolHtml, /class="brand app-brand"/);
  assert.match(toolHtml, /nav class="primary-nav"><a href="\/play">游戏大厅<\/a>/);
  assert.equal((toolHtml.match(/>游戏大厅<\/a>/g)||[]).length, 1);
  assert.doesNotMatch(toolHtml, /style="text-decoration:none"/);
  assert.match(toolHtml, /id="filterRegion"/);
  assert.match(toolHtml, /id="filterTeam"/);
  assert.match(toolHtml, /id="filterCountry"/);
  assert.match(toolHtml, /id="filterAgeMin"/);
  assert.match(toolHtml, /id="filterMajorWinsMin"/);
  assert.match(toolHtml, /id="filterMajorWinsMax"/);
  assert.match(toolHtml, /id="filterMajorAppsMin"/);
  assert.match(toolHtml, /id="filterMajorAppsMax"/);
  assert.match(toolHtml, /class="filter-combobox"/);
  assert.match(toolHtml, /data-candidate-sort="recommend"/);
  assert.match(toolHtml, /<section class="online-play-warning"/);
  assert.doesNotMatch(toolHtml, /<aside class="online-play-warning"/);
  assert.match(toolHtml, /我们不推荐在联机游玩时滥用此工具/);
  assert.doesNotMatch(toolHtml, /<select id="filter/);
  response = await fetch(base + "/js/app.js");
  const toolSource = await response.text();
  assert.match(toolSource, /applyCandidateFilters/);
  assert.match(toolSource, /populateCandidateFilters/);
  assert.match(toolSource, /bindCandidateFilter/);
  assert.match(toolSource, /data-filter-value/);
  assert.match(toolSource, /majorWinsMax/);
  assert.match(toolSource, /majorAppsMax/);
  assert.match(toolSource, /Flags\.flag/);
  assert.match(toolSource, /data-feedback-key/);
  assert.match(toolSource, /guess-card-enter/);
  assert.match(toolSource, /feedback-btn-change/);
  response = await fetch(base + "/css/hltv-overrides.css");
  const toolStyles = await response.text();
  assert.match(toolStyles, /\.avatar \{ width: 42px; height: 30px;/);
  assert.match(toolStyles, /object-fit: contain/);
  assert.doesNotMatch(toolStyles, /\.avatar img \{[^}]*object-fit: cover/);
  assert.match(toolStyles, /\.game-table td \.direction \{/);
  assert.match(toolStyles, /border:0!important/);
  assert.match(toolStyles, /@keyframes guessCellIn/);
  assert.match(toolStyles, /prefers-reduced-motion:reduce/);
  assert.match(toolStyles, /\.game-table thead \{ display:none; \}/);
  assert.match(toolStyles, /\.dialog-actions/);
  assert.match(toolStyles, /\.match-history-round/);
  assert.match(toolStyles, /\.match-format-lock/);
  assert.match(toolStyles, /\.home-mode-grid/);
  assert.match(toolStyles, /\.home-mode-card/);
  assert.match(toolStyles, /\.rules-dialog/);
  assert.match(toolStyles, /\.rules-feedback/);
  assert.match(toolStyles, /\.field-rule-list/);
  assert.match(toolStyles, /\.private-lobby-layout/);
  assert.match(toolStyles, /\.room-invite-dialog/);
  assert.match(toolStyles, /\.region-rule-grid/);
  assert.match(toolStyles, /@keyframes lobbyPlayerEnter/);
  assert.match(toolStyles, /@keyframes inviteDialogEnter/);
  assert.match(toolStyles, /@view-transition/);
  assert.match(toolStyles, /@keyframes pageForwardIn/);
  assert.match(toolStyles, /@keyframes pageBackIn/);
  assert.match(toolStyles, /@keyframes pageFallbackForwardIn/);
  assert.match(toolStyles, /ui-transition-fallback/);
  assert.match(toolStyles, /grid-template-columns:repeat\(2,minmax\(0,1fr\)\)/);
  assert.match(toolStyles, /\.online-play-warning/);
  assert.match(toolStyles, /#gameToast/);
  assert.match(toolStyles, /\.app-header/);
  assert.match(toolStyles, /grid-template-columns:210px minmax\(0,1fr\) auto/);
  assert.match(toolStyles, /font-size:15px!important/);
  assert.match(toolStyles, /Mobile-first guess density/);
  assert.ok(toolStyles.includes("grid-template-columns:repeat(7,minmax(0,1fr))"));
  assert.ok(toolStyles.includes(".game-page .game-table thead { display:table-header-group; }"));
  assert.ok(toolStyles.includes(".game-page .game-table td::before { content:none; display:none; }"));
  assert.ok(toolStyles.includes(".game-page .multiplayer-boards .board-card { max-height:238px;"));
  response = await fetch(base + "/js/flags.js");
  assert.equal(response.status, 200);
  const flagSource = await response.text();
  assert.match(flagSource, /中国香港特别行政区/);
  assert.ok(flagSource.includes("flagcdn.com/w80/"));
  response = await fetch(base + "/api/game/single", { method:"POST", headers:jsonHeaders, body:JSON.stringify({ playerName:"Test" }) });
  const single = await response.json();
  assert.equal(response.status, 201);
  response = await fetch(`${base}/api/game/single/${single.gameId}/guess`, { method:"POST", headers:playerHeaders(single.playerToken), body:JSON.stringify({ playerId:"Answer" }) });
  assert.equal((await response.json()).status, "won");

  response = await fetch(base + "/api/game/single", { method:"POST", headers:jsonHeaders, body:JSON.stringify({ playerName:"Beginner HTTP", questionMode:"beginner" }) });
  const beginnerHttp = await response.json();
  assert.equal(response.status, 201);
  assert.equal(beginnerHttp.state.questionMode, "beginner");
  response = await fetch(base + "/api/game/single/" + beginnerHttp.gameId + "/guess", { method:"POST", headers:playerHeaders(beginnerHttp.playerToken), body:JSON.stringify({ playerId:"Answer" }) });
  assert.equal(response.status, 400);
  response = await fetch(base + "/api/game/single/" + beginnerHttp.gameId + "/reveal", { method:"POST", headers:playerHeaders(beginnerHttp.playerToken) });
  const beginnerHttpReveal = await response.json();
  assert.equal(beginnerHttpReveal.answer.id, "P1");
  assert.equal(beginnerHttpReveal.answer.majorWins, 1);
  response = await fetch(base + "/api/rooms", { method:"POST", headers:jsonHeaders, body:JSON.stringify({ playerName:"Host", maxPlayers:3, scoreToWin:4, roundDurationSeconds:45 }) });
  const host = await response.json();
  assert.equal(response.status, 201);
  assert.match(host.roomCode, /^\d{6}$/);
  assert.equal(host.state.maxPlayers, 3);
  assert.equal(host.state.scoreToWin, 4);
  assert.equal(host.state.roundDurationSeconds, 45);
  assert.equal(host.state.status, "waiting");

  response = await fetch(`${base}/api/rooms/${host.roomCode}/join`, { method:"POST", headers:jsonHeaders, body:JSON.stringify({ playerName:"Guest" }) });
  const guest = await response.json();
  assert.equal(response.status, 200);
  assert.equal(guest.state.status, "waiting");

  response = await fetch(`${base}/api/rooms/${host.roomCode}/start`, { method:"POST", headers:playerHeaders(guest.playerToken) });
  assert.equal(response.status, 403);
  response = await fetch(`${base}/api/rooms/${host.roomCode}/ready`, { method:"POST", headers:playerHeaders(host.playerToken), body:JSON.stringify({ ready:true }) });
  assert.equal(response.status, 200);
  response = await fetch(`${base}/api/rooms/${host.roomCode}/ready`, { method:"POST", headers:playerHeaders(guest.playerToken), body:JSON.stringify({ ready:true }) });
  assert.equal((await response.json()).canStart, false);
  response = await fetch(`${base}/api/rooms/${host.roomCode}`, { headers:playerHeaders(host.playerToken) });
  assert.equal((await response.json()).canStart, true);
  response = await fetch(`${base}/api/rooms/${host.roomCode}/start`, { method:"POST", headers:playerHeaders(host.playerToken) });
  const startedPrivate = await response.json();
  assert.equal(startedPrivate.status, "playing");
  assert.equal(startedPrivate.roundDurationSeconds, 45);
  assert.equal(startedPrivate.roundDurationMs, 45_000);
  assert.ok(startedPrivate.timeLeftMs > 0 && startedPrivate.timeLeftMs <= 45_000);

  response = await fetch(`${base}/api/rooms/${host.roomCode}/join`, { method:"POST", headers:jsonHeaders, body:JSON.stringify({ playerName:"Late" }) });
  assert.equal(response.status, 409);
  response = await fetch(`${base}/api/rooms/${host.roomCode}/guess`, { method:"POST", headers:playerHeaders(host.playerToken), body:JSON.stringify({ playerId:"Answer" }) });
  const roundIntermission = await response.json();
  assert.equal(roundIntermission.status, "round_settling");
  assert.equal(roundIntermission.currentRound, 1);
  assert.equal(roundIntermission.answer.id, "Answer");
  assert.ok(roundIntermission.roundIntermissionLeftMs > 0 && roundIntermission.roundIntermissionLeftMs <= 5_000);

  response = await fetch(base + "/api/rooms", { method:"POST", headers:jsonHeaders, body:JSON.stringify({ playerName:"A" }) });
  const roomA = await response.json();
  response = await fetch(`${base}/api/rooms/${roomA.roomCode}/join`, { method:"POST", headers:jsonHeaders, body:JSON.stringify({ playerName:"B" }) });
  const roomB = await response.json();
  await fetch(`${base}/api/rooms/${roomA.roomCode}/ready`, { method:"POST", headers:playerHeaders(roomA.playerToken), body:JSON.stringify({ ready:true }) });
  await fetch(`${base}/api/rooms/${roomA.roomCode}/ready`, { method:"POST", headers:playerHeaders(roomB.playerToken), body:JSON.stringify({ ready:true }) });
  await fetch(`${base}/api/rooms/${roomA.roomCode}/start`, { method:"POST", headers:playerHeaders(roomA.playerToken) });
  response = await fetch(`${base}/api/rooms/${roomA.roomCode}/guess`, { method:"POST", headers:playerHeaders(roomA.playerToken), body:JSON.stringify({ playerId:"Answer" }) });
  assert.equal((await response.json()).status, "settling");

  response = await fetch(`${base}/api/rooms/${roomA.roomCode}/spectate`, { method:"POST", headers:jsonHeaders, body:JSON.stringify({ playerName:"Caster" }) });
  const spectator = await response.json();
  assert.equal(response.status, 200);
  assert.equal(spectator.state.viewerType, "spectator");

  response = await fetch(`${base}/api/rooms/${roomA.roomCode}/rematch`, { method:"POST", headers:playerHeaders(roomA.playerToken) });
  assert.equal((await response.json()).rematchCount, 1);
  response = await fetch(`${base}/api/rooms/${roomA.roomCode}/rematch`, { method:"POST", headers:playerHeaders(roomB.playerToken) });
  assert.equal((await response.json()).status, "playing");

  response = await fetch(base + "/api/game/single", { method:"POST", headers:jsonHeaders, body:JSON.stringify({ playerName:"Reveal HTTP" }) });
  const revealGame = await response.json();
  response = await fetch(`${base}/api/game/single/${revealGame.gameId}/reveal`, { method:"POST", headers:playerHeaders(revealGame.playerToken) });
  const revealedPayload = await response.json();
  assert.equal(response.status, 200);
  assert.equal(revealedPayload.finishReason, "revealed");
  assert.equal(revealedPayload.answer.id, "Answer");

  response = await fetch(base + "/api/rooms", { method:"POST", headers:jsonHeaders, body:JSON.stringify({ playerName:"Kick HTTP Host", maxPlayers:3 }) });
  const kickHttpHost = await response.json();
  response = await fetch(`${base}/api/rooms/${kickHttpHost.roomCode}/join`, { method:"POST", headers:jsonHeaders, body:JSON.stringify({ playerName:"Kick HTTP A" }) });
  const kickHttpGuestA = await response.json();
  response = await fetch(`${base}/api/rooms/${kickHttpHost.roomCode}/join`, { method:"POST", headers:jsonHeaders, body:JSON.stringify({ playerName:"Kick HTTP B" }) });
  const kickHttpGuestB = await response.json();
  response = await fetch(`${base}/api/rooms/${kickHttpHost.roomCode}/kick`, { method:"POST", headers:playerHeaders(kickHttpGuestA.playerToken), body:JSON.stringify({ playerId:kickHttpGuestB.playerId }) });
  assert.equal(response.status, 403);
  response = await fetch(`${base}/api/rooms/${kickHttpHost.roomCode}/kick`, { method:"POST", headers:playerHeaders(kickHttpHost.playerToken), body:JSON.stringify({ playerId:kickHttpGuestA.playerId }) });
  const kickedHttpState = await response.json();
  assert.equal(response.status, 200);
  assert.equal(kickedHttpState.players.length, 2);
  response = await fetch(`${base}/api/rooms/${kickHttpHost.roomCode}`, { headers:playerHeaders(kickHttpGuestA.playerToken) });
  const kickedHttpError = await response.json();
  assert.equal(response.status, 403);
  assert.match(kickedHttpError.error, /房主/);
  response = await fetch(`${base}/api/rooms/${kickHttpHost.roomCode}/kick`, { method:"POST", headers:playerHeaders(kickHttpHost.playerToken), body:JSON.stringify({ playerId:kickHttpHost.playerId }) });
  assert.equal(response.status, 409);
  response = await fetch(base + "/api/rooms", { method:"POST", headers:jsonHeaders, body:JSON.stringify({ playerName:"Leaving HTTP Host" }) });
  const leavingHostHttp = await response.json();
  response = await fetch(`${base}/api/rooms/${leavingHostHttp.roomCode}/join`, { method:"POST", headers:jsonHeaders, body:JSON.stringify({ playerName:"Leaving HTTP Guest" }) });
  const leavingGuestHttp = await response.json();
  response = await fetch(`${base}/api/rooms/${leavingHostHttp.roomCode}`, { method:"DELETE", headers:playerHeaders(leavingGuestHttp.playerToken) });
  const guestLeavePayload = await response.json();
  assert.equal(response.status, 200);
  assert.equal(guestLeavePayload.viewerType, "player");
  response = await fetch(`${base}/api/rooms/${leavingHostHttp.roomCode}`, { headers:playerHeaders(leavingHostHttp.playerToken) });
  const hostAfterGuestLeave = await response.json();
  assert.equal(hostAfterGuestLeave.players.length, 1);
  response = await fetch(`${base}/api/rooms/${leavingHostHttp.roomCode}`, { method:"DELETE", headers:playerHeaders(leavingHostHttp.playerToken) });
  const hostLeavePayload = await response.json();
  assert.equal(response.status, 200);
  assert.equal(hostLeavePayload.dissolved, true);
  response = await fetch(`${base}/api/rooms/${leavingHostHttp.roomCode}`, { headers:playerHeaders(leavingHostHttp.playerToken) });
  assert.equal(response.status, 404);
} finally {
  await app.close();
}

console.log("app-server.test.mjs: all HTTP flows passed");
